site_name: poetry_cookiecutter_instance
repo_name: poetry_cookiecutter_instance
copyright: Copyright &copy; 2021 - 2022 Quentin Blampey
theme:
  name: material
nav:
  - Home: index.md
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js